server:
  port: 8032
management:
  server:
    port: 8033
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/project
    username: userapi
    password: userapipassword
