version: '3'
services:
  mysql-api:
    image: "breno1112/spring-mysql-api"
    ports:
      - "8082:8082"
  mysql-server:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../../mysql/scripts/:/docker-entrypoint-initdb.d/